# group_vars/backup_target.yml
# (선택) backup 대상 DB의 VIP 정의 (SQL 라우팅용)

pg_vip_host: "10.2.3.254"
pg_vip_port: 5432
pg_data_path: "/var/lib/pgsql/patroni"

pgbackrest_stanza: "main"
pg_backup_db_user: "postgres"
pg_backup_db_password: "CHANGE_ME"

