$ANSIBLE_VAULT;1.1;AES256
31336661373637626434333433303036336531353162393332343730326633343535656130323231
6237623938623864663761653736313636363132623165360a343032373066376139323337646437
36313963633861663630613537633038653138383232333837346234323761363334356362616338
3830316433323164630a313263383837633335653633363066336564646162323833366131336333
33633962636165626533653532613133346562343134363637373161623230663334633234303862
63666137396438306464383433326330363965333430343634356134653465363637393635383337
62623234303132306433326339343737666564316261663764613435636462303130366339326434
62326561376630376537346231633035613562663436313239343834303866366239653862393164
30316635643335643336323661363462653861656661376462316563356130633361616232313866
62613135313732633962653234626663326436656435663538303737386331636639306132343939
35313131333033386231663737333862333332663165353866376164653136306566383163633334
32363434396161323263653635313265373363366562663133643139343637303762636335326235
32373735386661653936383264336264656335303638653839346131616566653362356463616531
39343632326438366336666437323661373664376335666663313961323135643164353639636333
35633139636664313732333335653835383666613064613066616533653564646466653939323730
30346133663637656633383965333430633235653138646334613530373434656265333035653735
35643362313135633930303632393062316132646639346437363363386366323233
