---
pgbackrest_stanza: "main"
# NFS export directory (backup repository)
backup_nfs_export_dir: "/exports/pgbackrest"

# NFS mount point on clients
backup_nfs_mount_point: "/var/lib/pgbackrest"

# NFS server host (inventory group 'backup_server' 첫번째를 기본으로 사용)
backup_nfs_server_host: "{{ groups['backup_server'][0] | default('storageVM') }}"

